In [14]:
import numpy as np
import itertools

class HiddenMarkovModel:
    def __init__(self, num_states, num_emissions):
        self.num_states = num_states
        self.num_emissions = num_emissions
        self.states = range(num_states)
        self.emissions = range(num_emissions)
        self.transition_matrix = np.random.rand(num_states, num_states)
        self.emission_matrix = np.random.rand(num_states, num_emissions)
        self.start_probabilities = np.random.rand(num_states)
        self.normalize_matrices()

    def normalize_matrices(self):
        self.transition_matrix /= self.transition_matrix.sum(axis=1, keepdims=True)
        self.emission_matrix /= self.emission_matrix.sum(axis=1, keepdims=True)
        self.start_probabilities /= self.start_probabilities.sum()

    def update_matrix(self, matrix_type, row, col, value):
        if matrix_type == 'transition':
            self.transition_matrix[row, col] = value
        elif matrix_type == 'emission':
            self.emission_matrix[row, col] = value
        self.normalize_matrices()
  
    def valid_emission(self, state, emission):
        return self.emission_matrix[state, emission] > 0

    def valid_transition(self, from_state, to_state):
        return self.transition_matrix[from_state, to_state] > 0

    def emission_set(self):
        return {e for s in self.states for e in self.emissions if self.valid_emission(s, e)}
  
    def calculate_probability(self, state_seq, emission_seq):
        probability = self.start_probabilities[state_seq[0]]
        for i, state in enumerate(state_seq):
            if i > 0:
                probability *= self.transition_matrix[state_seq[i - 1], state]
            probability *= self.emission_matrix[state, emission_seq[i]]
        return probability

    def HMM_path(self, emission_seq):
        all_paths = itertools.product(self.states, repeat=len(emission_seq))
        max_prob = 0
        most_probable_path = None

        for path in all_paths:
            prob = self.calculate_probability(path, emission_seq)
           # if prob != 0:
            print("path and probablity",path,prob)
            if prob > max_prob:
                max_prob = prob
                most_probable_path = path

        return most_probable_path, max_prob

# Example Usage
num_states = int(input("enter number of states "))       # Number of states
num_emissions = int(input("Enter number of emissions "))    # Number of emissions
hmm = HiddenMarkovModel(num_states, num_emissions)

# Update matrices with zero values (representing impossible transitions/emissions)
hmm.update_matrix('transition', 0, 1, 0)  # State 0 cannot transition to State 1
hmm.update_matrix('emission', 1, 0, 0)    # State 1 does not emit Emission 0


# Display matrices
print("Transition Matrix:\n", hmm.transition_matrix)
print("Emission Matrix:\n", hmm.emission_matrix)
print("Start Probabilities:\n", hmm.start_probabilities)

# Calculate the most probable path
obs_seq = input("Enter emission sequence") 
#if len(obs_seq) <= num_emissions:
obs_seq = [int(num) for num in obs_seq]
most_probable_path, max_prob = hmm.HMM_path(obs_seq)
print("Most Probable Path:", most_probable_path)
print("Probability of the Path:", max_prob)
  

enter number of states 4
Enter number of emissions 3
Transition Matrix:
 [[0.42563071 0.         0.14398028 0.43038901]
 [0.40363543 0.36290112 0.09808191 0.13538154]
 [0.05726609 0.44304162 0.08238269 0.41730961]
 [0.24974681 0.26856672 0.39697295 0.08471352]]
Emission Matrix:
 [[0.41796997 0.35453095 0.22749908]
 [0.         0.33279884 0.66720116]
 [0.19457026 0.4190822  0.38634754]
 [0.35517917 0.32581382 0.319007  ]]
Start Probabilities:
 [0.27296867 0.28721163 0.39603955 0.04378016]
Enter emission sequence00122
path and probablity (0, 0, 0, 0, 0) 2.871760586983583e-05
path and probablity (0, 0, 0, 0, 1) 0.0
path and probablity (0, 0, 0, 0, 2) 1.6497449243416232e-05
path and probablity (0, 0, 0, 0, 3) 4.07189922982403e-05
path and probablity (0, 0, 0, 1, 0) 0.0
path and probablity (0, 0, 0, 1, 1) 0.0
path and probablity (0, 0, 0, 1, 2) 0.0
path and probablity (0, 0, 0, 1, 3) 0.0
path and probablity (0, 0, 0, 2, 0) 2.2196338534956644e-06
path and probablity (0, 0, 0, 2, 1) 5.0362296

'\nelse:\n    print("Enter proper emission sequence")\n'